workflows:
  android-release:
    name: Lakshya Digital Library Android
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Generate modern Android project
        script: |
          rm -rf android
          flutter create --platforms=android --org com.lakshyadigitallibrary .
      - name: Build Android APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
